### ISSUE TITLE
Installation...

### ISSUE THREAD

**Issue by Andy-ABTec** [the-black-eagle/script.radio.streaming.helper#3]
Apologies for the dumb question, but are there any installation instructions?

Just a few pointers would do... (having trouble, edited MusicVisualisation.xml but not sure what else I need to do to get a sensible display for "Planet Rock")

(Using the latest Kodi Krypton with Estuary on Win 10 and Linux)

Ta!

Andy B.

**Comment by the-black-eagle** [comment]
If you click on the 'Clone or download' button on the code page, you'll see the option to download as a zip file.  You can then install the addon via Kodi's 'install from zip file' option.  You will need to enable installation of addons from unknown sources first.

I'm not sure if it ever got fixed, but Krypton didn't pass meta-data from internet streams correctly, meaning that there was no data for the addon to work with. I wrote it originally for V16 (which I still use) and everything works as expected there.

**Comment by Andy-ABTec** [comment]
Mmm, done all of that already but it doesn't seem as if the script is even running, can you confirm which windows directories the MusicVisualisation.xml and the actual adon should be in please...

Thanks,

Andy B.

**Comment by the-black-eagle** [comment]
Yeah.  On Windows, the path to the addon should be '%APPDATA%\kodi\addons\script.radio.streaming.helper\

The path to the MusicVisualisation.xml will depend upon which skin you are altering to display the data from the addon but it'll be something like '%APPDATA%\addons\skin.AeonMQ7\1080i\MusicVisualisation.xml'

On Linux the paths are similar in that the addon would be at '~/.kodi/addons/script.radio.streaming.helper' and the skin at '~/.kodi/addons/skin.aeonmq7/MusicVisualisation.xml'

**Comment by Andy-ABTec** [comment]
Already had everything in the right place, no joy still...

Guessing its a Krypton/Estuary issue 😞 

Anyway, thanks for your time...

**Comment by the-black-eagle** [comment]
You could always try installing v16 in portable mode https://kodi.wiki/view/HOW-TO:Install_Kodi_for_Windows#Portable_Mode

There is a modded version of Musicvisualisation.xml for AeonMQ7 at https://github.com/the-black-eagle/MQ7-MusicVisualisation.mod/blob/master/MusicVisualisation.xml

**Comment by Andy-ABTec** [comment]
OK thanks for the pointers...
